/**
 * Default model seed data. Populated on first run if models table is empty.
 * Contains metadata only — no model weights are downloaded.
 */
import type { ModelRecord } from './models.ts';

type SeedModel = Omit<ModelRecord, 'created_at' | 'last_seen_at' | 'is_local'>;

export const MODEL_SEEDS: SeedModel[] = [
  // ── Ollama Local Models ───────────────────────────────────────────────────
  {
    id: 'ollama:qwen2.5:0.5b',
    name: 'qwen2.5:0.5b',
    display_name: 'Qwen 2.5 0.5B',
    provider: 'ollama',
    parameter_count: 0.5,
    context_length: 8192,
    min_ram: 2,
    min_vram: 0,
    speed_rank: 1,
    download_url: 'https://ollama.com/library/qwen2.5',
    download_command: 'ollama pull qwen2.5:0.5b',
    tags: 'local,tiny,fast,qwen',
  },
  {
    id: 'ollama:qwen2.5:1.5b',
    name: 'qwen2.5:1.5b',
    display_name: 'Qwen 2.5 1.5B',
    provider: 'ollama',
    parameter_count: 1.5,
    context_length: 8192,
    min_ram: 4,
    min_vram: 0,
    speed_rank: 2,
    download_url: 'https://ollama.com/library/qwen2.5',
    download_command: 'ollama pull qwen2.5:1.5b',
    tags: 'local,small,fast,qwen',
  },
  {
    id: 'ollama:qwen2.5:3b',
    name: 'qwen2.5:3b',
    display_name: 'Qwen 2.5 3B',
    provider: 'ollama',
    parameter_count: 3,
    context_length: 16384,
    min_ram: 6,
    min_vram: 0,
    speed_rank: 3,
    download_url: 'https://ollama.com/library/qwen2.5',
    download_command: 'ollama pull qwen2.5:3b',
    tags: 'local,medium,qwen',
  },
  {
    id: 'ollama:qwen2.5-coder:1.5b',
    name: 'qwen2.5-coder:1.5b',
    display_name: 'Qwen 2.5 Coder 1.5B',
    provider: 'ollama',
    parameter_count: 1.5,
    context_length: 32768,
    min_ram: 4,
    min_vram: 0,
    speed_rank: 2,
    download_url: 'https://ollama.com/library/qwen2.5-coder',
    download_command: 'ollama pull qwen2.5-coder:1.5b',
    tags: 'local,coding,fast,qwen',
  },
  {
    id: 'ollama:qwen2.5-coder:3b',
    name: 'qwen2.5-coder:3b',
    display_name: 'Qwen 2.5 Coder 3B',
    provider: 'ollama',
    parameter_count: 3,
    context_length: 32768,
    min_ram: 6,
    min_vram: 0,
    speed_rank: 3,
    download_url: 'https://ollama.com/library/qwen2.5-coder',
    download_command: 'ollama pull qwen2.5-coder:3b',
    tags: 'local,coding,medium,qwen',
  },
  {
    id: 'ollama:qwen2.5-coder:7b',
    name: 'qwen2.5-coder:7b',
    display_name: 'Qwen 2.5 Coder 7B',
    provider: 'ollama',
    parameter_count: 7,
    context_length: 32768,
    min_ram: 12,
    min_vram: 6,
    speed_rank: 5,
    download_url: 'https://ollama.com/library/qwen2.5-coder',
    download_command: 'ollama pull qwen2.5-coder:7b',
    tags: 'local,coding,qwen',
  },
  {
    id: 'ollama:qwen2.5-coder:14b',
    name: 'qwen2.5-coder:14b',
    display_name: 'Qwen 2.5 Coder 14B',
    provider: 'ollama',
    parameter_count: 14,
    context_length: 32768,
    min_ram: 20,
    min_vram: 10,
    speed_rank: 7,
    download_url: 'https://ollama.com/library/qwen2.5-coder',
    download_command: 'ollama pull qwen2.5-coder:14b',
    tags: 'local,coding,large,qwen',
  },
  {
    id: 'ollama:llama3.2:1b',
    name: 'llama3.2:1b',
    display_name: 'Llama 3.2 1B',
    provider: 'ollama',
    parameter_count: 1,
    context_length: 131072,
    min_ram: 3,
    min_vram: 0,
    speed_rank: 1,
    download_url: 'https://ollama.com/library/llama3.2',
    download_command: 'ollama pull llama3.2:1b',
    tags: 'local,tiny,llama,meta',
  },
  {
    id: 'ollama:llama3.2:3b',
    name: 'llama3.2:3b',
    display_name: 'Llama 3.2 3B',
    provider: 'ollama',
    parameter_count: 3,
    context_length: 131072,
    min_ram: 6,
    min_vram: 0,
    speed_rank: 3,
    download_url: 'https://ollama.com/library/llama3.2',
    download_command: 'ollama pull llama3.2:3b',
    tags: 'local,small,llama,meta',
  },
  {
    id: 'ollama:llama3.1:8b',
    name: 'llama3.1:8b',
    display_name: 'Llama 3.1 8B',
    provider: 'ollama',
    parameter_count: 8,
    context_length: 131072,
    min_ram: 12,
    min_vram: 6,
    speed_rank: 5,
    download_url: 'https://ollama.com/library/llama3.1',
    download_command: 'ollama pull llama3.1:8b',
    tags: 'local,medium,llama,meta',
  },
  {
    id: 'ollama:mistral:7b',
    name: 'mistral:7b',
    display_name: 'Mistral 7B',
    provider: 'ollama',
    parameter_count: 7,
    context_length: 32768,
    min_ram: 10,
    min_vram: 4,
    speed_rank: 5,
    download_url: 'https://ollama.com/library/mistral',
    download_command: 'ollama pull mistral:7b',
    tags: 'local,medium,mistral',
  },
  {
    id: 'ollama:phi3:mini',
    name: 'phi3:mini',
    display_name: 'Phi-3 Mini 3.8B',
    provider: 'ollama',
    parameter_count: 3.8,
    context_length: 128000,
    min_ram: 6,
    min_vram: 0,
    speed_rank: 3,
    download_url: 'https://ollama.com/library/phi3',
    download_command: 'ollama pull phi3:mini',
    tags: 'local,coding,small,phi,microsoft',
  },
  {
    id: 'ollama:phi3.5:mini',
    name: 'phi3.5:mini',
    display_name: 'Phi-3.5 Mini 3.8B',
    provider: 'ollama',
    parameter_count: 3.8,
    context_length: 128000,
    min_ram: 6,
    min_vram: 0,
    speed_rank: 3,
    download_url: 'https://ollama.com/library/phi3.5',
    download_command: 'ollama pull phi3.5:mini',
    tags: 'local,small,phi,microsoft',
  },
  {
    id: 'ollama:deepseek-coder:1.3b',
    name: 'deepseek-coder:1.3b',
    display_name: 'DeepSeek Coder 1.3B',
    provider: 'ollama',
    parameter_count: 1.3,
    context_length: 16384,
    min_ram: 4,
    min_vram: 0,
    speed_rank: 2,
    download_url: 'https://ollama.com/library/deepseek-coder',
    download_command: 'ollama pull deepseek-coder:1.3b',
    tags: 'local,coding,tiny,deepseek',
  },
  {
    id: 'ollama:deepseek-coder:6.7b',
    name: 'deepseek-coder:6.7b',
    display_name: 'DeepSeek Coder 6.7B',
    provider: 'ollama',
    parameter_count: 6.7,
    context_length: 16384,
    min_ram: 10,
    min_vram: 4,
    speed_rank: 5,
    download_url: 'https://ollama.com/library/deepseek-coder',
    download_command: 'ollama pull deepseek-coder:6.7b',
    tags: 'local,coding,medium,deepseek',
  },
  {
    id: 'ollama:codellama:7b',
    name: 'codellama:7b',
    display_name: 'Code Llama 7B',
    provider: 'ollama',
    parameter_count: 7,
    context_length: 16384,
    min_ram: 10,
    min_vram: 4,
    speed_rank: 5,
    download_url: 'https://ollama.com/library/codellama',
    download_command: 'ollama pull codellama:7b',
    tags: 'local,coding,llama,meta',
  },
  {
    id: 'ollama:gemma2:2b',
    name: 'gemma2:2b',
    display_name: 'Gemma 2 2B',
    provider: 'ollama',
    parameter_count: 2,
    context_length: 8192,
    min_ram: 4,
    min_vram: 0,
    speed_rank: 2,
    download_url: 'https://ollama.com/library/gemma2',
    download_command: 'ollama pull gemma2:2b',
    tags: 'local,small,gemma,google',
  },
  {
    id: 'ollama:gemma2:9b',
    name: 'gemma2:9b',
    display_name: 'Gemma 2 9B',
    provider: 'ollama',
    parameter_count: 9,
    context_length: 8192,
    min_ram: 14,
    min_vram: 6,
    speed_rank: 6,
    download_url: 'https://ollama.com/library/gemma2',
    download_command: 'ollama pull gemma2:9b',
    tags: 'local,medium,gemma,google',
  },
  {
    id: 'ollama:tinyllama:1.1b',
    name: 'tinyllama:1.1b',
    display_name: 'TinyLlama 1.1B',
    provider: 'ollama',
    parameter_count: 1.1,
    context_length: 2048,
    min_ram: 2,
    min_vram: 0,
    speed_rank: 1,
    download_url: 'https://ollama.com/library/tinyllama',
    download_command: 'ollama pull tinyllama:1.1b',
    tags: 'local,tiny,ultrafast,llama',
  },
  {
    id: 'ollama:smollm2:1.7b',
    name: 'smollm2:1.7b',
    display_name: 'SmolLM2 1.7B',
    provider: 'ollama',
    parameter_count: 1.7,
    context_length: 8192,
    min_ram: 3,
    min_vram: 0,
    speed_rank: 2,
    download_url: 'https://ollama.com/library/smollm2',
    download_command: 'ollama pull smollm2:1.7b',
    tags: 'local,tiny,fast,huggingface',
  },
  // `tiiuae/Falcon-H1-1.5B-Deep-Instruct` from HF (safetensors, not GGUF).
  // To use in Ollama, create a Modelfile with:
  //   FROM tiiuae/Falcon-H1-1.5B-Deep-Instruct
  // Then: ollama create falcon-h1-1.5b -f Modelfile
  // This lets Ollama auto-download and quantize from HuggingFace.
  {
    id: 'ollama:falcon-h1-1.5b-deep-instruct',
    name: 'falcon-h1-1.5b-deep-instruct',
    display_name: 'Falcon-H1 1.5B Deep Instruct (HF import)',
    provider: 'ollama',
    parameter_count: 1.5,
    context_length: 8192,
    min_ram: 3,
    min_vram: 0,
    speed_rank: 2,
    download_url: 'https://huggingface.co/tiiuae/Falcon-H1-1.5B-Deep-Instruct',
    download_command: 'echo "create Modelfile with: FROM tiiuae/Falcon-H1-1.5B-Deep-Instruct && ollama create falcon-h1-1.5b -f Modelfile"',
    tags: 'local,small,fast,falcon,tiiuae,reasoning,hf-import',
  },
  {
    id: 'ollama:nomic-embed-text',
    name: 'nomic-embed-text',
    display_name: 'Nomic Embed Text',
    provider: 'ollama',
    parameter_count: 0.137,
    context_length: 8192,
    min_ram: 1,
    min_vram: 0,
    speed_rank: 1,
    download_url: 'https://ollama.com/library/nomic-embed-text',
    download_command: 'ollama pull nomic-embed-text',
    tags: 'local,embedding,nomic',
  },
  // ── OpenRouter Free Models ────────────────────────────────────────────────
  {
    id: 'openrouter:qwen/qwen-2.5-coder-1.5b-instruct:free',
    name: 'qwen/qwen-2.5-coder-1.5b-instruct:free',
    display_name: 'Qwen 2.5 Coder 1.5B (Free)',
    provider: 'openrouter',
    parameter_count: 1.5,
    context_length: 32768,
    min_ram: 0,
    min_vram: 0,
    speed_rank: 2,
    download_url: 'https://openrouter.ai/qwen/qwen-2.5-coder-1.5b-instruct:free',
    download_command: '',
    tags: 'cloud,free,coding,fast,qwen',
  },
  {
    id: 'openrouter:google/gemma-3-4b-it:free',
    name: 'google/gemma-3-4b-it:free',
    display_name: 'Gemma 3 4B (Free)',
    provider: 'openrouter',
    parameter_count: 4,
    context_length: 131072,
    min_ram: 0,
    min_vram: 0,
    speed_rank: 3,
    download_url: 'https://openrouter.ai/google/gemma-3-4b-it:free',
    download_command: '',
    tags: 'cloud,free,gemma,google',
  },
  {
    id: 'openrouter:meta-llama/llama-3.2-3b-instruct:free',
    name: 'meta-llama/llama-3.2-3b-instruct:free',
    display_name: 'Llama 3.2 3B (Free)',
    provider: 'openrouter',
    parameter_count: 3,
    context_length: 131072,
    min_ram: 0,
    min_vram: 0,
    speed_rank: 3,
    download_url: 'https://openrouter.ai/meta-llama/llama-3.2-3b-instruct:free',
    download_command: '',
    tags: 'cloud,free,llama,meta',
  },
  {
    id: 'openrouter:mistralai/mistral-7b-instruct:free',
    name: 'mistralai/mistral-7b-instruct:free',
    display_name: 'Mistral 7B (Free)',
    provider: 'openrouter',
    parameter_count: 7,
    context_length: 32768,
    min_ram: 0,
    min_vram: 0,
    speed_rank: 5,
    download_url: 'https://openrouter.ai/mistralai/mistral-7b-instruct:free',
    download_command: '',
    tags: 'cloud,free,mistral',
  },
  {
    id: 'openrouter:deepseek/deepseek-r1:free',
    name: 'deepseek/deepseek-r1:free',
    display_name: 'DeepSeek R1 (Free)',
    provider: 'openrouter',
    parameter_count: 671,
    context_length: 65536,
    min_ram: 0,
    min_vram: 0,
    speed_rank: 15,
    download_url: 'https://openrouter.ai/deepseek/deepseek-r1:free',
    download_command: '',
    tags: 'cloud,free,reasoning,deepseek',
  },
  // ── OpenAI Models ──────────────────────────────────────────────────────────
  {
    id: 'openai:gpt-4o-mini',
    name: 'gpt-4o-mini',
    display_name: 'GPT-4o Mini',
    provider: 'openai',
    parameter_count: 8,
    context_length: 128000,
    min_ram: 0,
    min_vram: 0,
    speed_rank: 4,
    download_url: 'https://platform.openai.com/docs/models/gpt-4o-mini',
    download_command: '',
    tags: 'cloud,openai,fast',
  },
  {
    id: 'openai:gpt-4o',
    name: 'gpt-4o',
    display_name: 'GPT-4o',
    provider: 'openai',
    parameter_count: 200,
    context_length: 128000,
    min_ram: 0,
    min_vram: 0,
    speed_rank: 9,
    download_url: 'https://platform.openai.com/docs/models/gpt-4o',
    download_command: '',
    tags: 'cloud,openai,flagship',
  },
  // ── Anthropic Models ───────────────────────────────────────────────────────
  {
    id: 'anthropic:claude-haiku-3-5',
    name: 'claude-3-5-haiku-latest',
    display_name: 'Claude 3.5 Haiku',
    provider: 'anthropic',
    parameter_count: 20,
    context_length: 200000,
    min_ram: 0,
    min_vram: 0,
    speed_rank: 4,
    download_url: 'https://www.anthropic.com/claude/haiku',
    download_command: '',
    tags: 'cloud,anthropic,fast',
  },
  {
    id: 'anthropic:claude-sonnet-3-7',
    name: 'claude-sonnet-4-5',
    display_name: 'Claude Sonnet 4.5',
    provider: 'anthropic',
    parameter_count: 70,
    context_length: 200000,
    min_ram: 0,
    min_vram: 0,
    speed_rank: 8,
    download_url: 'https://www.anthropic.com/claude/sonnet',
    download_command: '',
    tags: 'cloud,anthropic,flagship',
  },
  // ── Google Gemini Models ───────────────────────────────────────────────────
  {
    id: 'gemini:gemini-2.0-flash',
    name: 'gemini-2.0-flash',
    display_name: 'Gemini 2.0 Flash',
    provider: 'gemini',
    parameter_count: 8,
    context_length: 1048576,
    min_ram: 0,
    min_vram: 0,
    speed_rank: 3,
    download_url: 'https://ai.google.dev/gemini-api/docs/models',
    download_command: '',
    tags: 'cloud,google,fast,gemini',
  },
  {
    id: 'gemini:gemini-1.5-flash',
    name: 'gemini-1.5-flash',
    display_name: 'Gemini 1.5 Flash',
    provider: 'gemini',
    parameter_count: 8,
    context_length: 1048576,
    min_ram: 0,
    min_vram: 0,
    speed_rank: 3,
    download_url: 'https://ai.google.dev/gemini-api/docs/models',
    download_command: '',
    tags: 'cloud,google,fast,gemini',
  },
  // ── Nvidia NIM Models ─────────────────────────────────────────────────────
  {
    id: 'nvidia:meta/llama-3.2-3b-instruct',
    name: 'meta/llama-3.2-3b-instruct',
    display_name: 'Llama 3.2 3B (Nvidia NIM)',
    provider: 'nvidia',
    parameter_count: 3,
    context_length: 131072,
    min_ram: 0,
    min_vram: 0,
    speed_rank: 3,
    download_url: 'https://build.nvidia.com/meta/llama-3_2-3b-instruct',
    download_command: '',
    tags: 'cloud,nvidia,nim,llama,meta',
  },
  {
    id: 'nvidia:qwen/qwen2.5-coder-7b-instruct',
    name: 'qwen/qwen2.5-coder-7b-instruct',
    display_name: 'Qwen 2.5 Coder 7B (Nvidia NIM)',
    provider: 'nvidia',
    parameter_count: 7,
    context_length: 32768,
    min_ram: 0,
    min_vram: 0,
    speed_rank: 5,
    download_url: 'https://build.nvidia.com/qwen/qwen2_5-coder-7b-instruct',
    download_command: '',
    tags: 'cloud,nvidia,nim,coding,qwen',
  },
  {
    id: 'nvidia:google/gemma-3-4b-it',
    name: 'google/gemma-3-4b-it',
    display_name: 'Gemma 3 4B (Nvidia NIM)',
    provider: 'nvidia',
    parameter_count: 4,
    context_length: 131072,
    min_ram: 0,
    min_vram: 0,
    speed_rank: 3,
    download_url: 'https://build.nvidia.com/google/gemma-3-4b-it',
    download_command: '',
    tags: 'cloud,nvidia,nim,gemma,google',
  },
  // ── Groq Models ────────────────────────────────────────────────────────────
  {
    id: 'groq:llama-3.1-8b-instant',
    name: 'llama-3.1-8b-instant',
    display_name: 'Llama 3.1 8B Instant (Groq)',
    provider: 'groq',
    parameter_count: 8,
    context_length: 131072,
    min_ram: 0,
    min_vram: 0,
    speed_rank: 2,
    download_url: 'https://console.groq.com/docs/models',
    download_command: '',
    tags: 'cloud,groq,fast,llama,meta',
  },
  {
    id: 'groq:qwen-qwq-32b',
    name: 'qwen-qwq-32b',
    display_name: 'Qwen QwQ 32B (Groq)',
    provider: 'groq',
    parameter_count: 32,
    context_length: 32768,
    min_ram: 0,
    min_vram: 0,
    speed_rank: 6,
    download_url: 'https://console.groq.com/docs/models',
    download_command: '',
    tags: 'cloud,groq,reasoning,qwen',
  },
  {
    id: 'groq:gemma2-9b-it',
    name: 'gemma2-9b-it',
    display_name: 'Gemma 2 9B (Groq)',
    provider: 'groq',
    parameter_count: 9,
    context_length: 8192,
    min_ram: 0,
    min_vram: 0,
    speed_rank: 4,
    download_url: 'https://console.groq.com/docs/models',
    download_command: '',
    tags: 'cloud,groq,gemma,google',
  },
];
